[package]
name = "tletools"
version = "0.1.0"
description = "Library to work with two-line element set files"
authors = ["Federico Stra <stra.federico@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
